- alias: iPad Air found
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.7481140cba2b
    from: 'not_home'
    to: 'home'
  action:
    service: notify.macmurph42
    data_template:
      title: "iPad Air gefunden."
      message: "iPad Air ist jetzt zu Hause angemeldet."

