# iPad 4: 04e5364362fc
- alias: iPad4 away
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.04e5364362fc
    from: 'home'
    to: 'not_home'
  action:
    service: notify.macmurph42
    data_template:
      title: "iPad 4 abgemeldet."
      message: "iPad 4 nicht mehr zu Hause angemeldet."
