# Turn wemo switch kitchen on/off when kitchen table goes on/off
- alias: 'Turn on kitchen table switch' 
  initial_state: True
  hide_entity: True 
  trigger:
    platform: state
    entity_id: light.kitchen_table
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on 
    entity_id: switch.kitchen

- alias: 'Turn off kitchen table switch' 
  initial_state: True
  hide_entity: True 
  trigger:
    platform: state
    entity_id: light.kitchen_table
    from: 'on'
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.kitchen
